package src;

//IN ORDER TO INHERIT FIELDS/METHODS FROM THE ANIMAL CLASS INTO THE DOG SUBCLASS, WE USE THE 'EXTENDS' KEYWORD AND REFERENCE THE ANIMAL CLASS RIGHT AFTER
public class Dog extends Animal {

    private int eyes;
    private int legs;
    private int tail;
    private int teeth;
    private int coat;
    //ALTHOUGH PRIVATE FIELDS HAVE BEEN INHERITED FROM THE ANIMAL SUPERCLASS, THE PRIVATE FIELDS ABOVE REPRESENT ATTR THAT ARE SPECIFIC TO THE DOG SUBCLASS AND MAY NOT BE VALID IN OTHER SUBCLASSES OF ANIMALS


    public Dog(String name, int brain, int body, int size, int weight) {
        super(name, brain, body, size, weight);
    }
    //THIS CONSTRUCTOR WAS AUTOMATICALLY GENERATED USING THE CMD+N KEYBINDING. AS WE CAN SEE, ALL THE APPROPRIATE FIELDS ARE PASSED AS PARAMETERS. 'SUPER' REFERS TO THE ANIMAL SUPER-CLASS WHERE THESE FIELDS ARE BEING INHERITED FROM.
}
